import type { ProductGeneratedTestCase } from "../../../types";

export function renderGeneratedProductApiTestSource(
  targetId: string,
  baseUrl: string,
  sourceSchemaPath: string,
  tests: ProductGeneratedTestCase[],
  allowDestructiveActions: boolean
): string {
  const lines = [
    "import { test } from '@playwright/test';",
    "",
    "// @generated by CodeDecay. Review before promoting into your permanent test suite.",
    `// codedecay:source-openapi-schema=${sourceSchemaPath}`,
    `// codedecay:target=${targetId}`,
    "",
    `const CODEDECAY_API_BASE_URL = process.env.CODEDECAY_PRODUCT_BASE_URL ?? ${JSON.stringify(baseUrl)};`,
    "",
    "function apiUrl(path: string): string {",
    "  return new URL(path, CODEDECAY_API_BASE_URL.endsWith('/') ? CODEDECAY_API_BASE_URL : `${CODEDECAY_API_BASE_URL}/`).toString();",
    "}",
    "",
    "async function responseSnippet(response: { text: () => Promise<string> }): Promise<string> {",
    "  try {",
    "    return (await response.text()).replace(/\\s+/g, ' ').trim().slice(0, 500);",
    "  } catch {",
    "    return '';",
    "  }",
    "}",
    "",
    `test.describe(${JSON.stringify(`CodeDecay generated API regression tests (${targetId})`)}, () => {`
  ];

  for (const testCase of tests) {
    const declaration = testCase.destructive && !allowDestructiveActions ? "test.skip" : "test";
    lines.push(
      "",
      `  ${declaration}(${JSON.stringify(testCase.title)}, async ({ request }) => {`,
      `    test.info().annotations.push({ type: 'codedecay.testId', description: ${JSON.stringify(testCase.id)} });`
    );
    appendGeneratedApiTestBody(lines, testCase);
    lines.push("  });");
  }

  lines.push("});", "");
  return lines.join("\n");
}

function appendGeneratedApiTestBody(lines: string[], testCase: ProductGeneratedTestCase): void {
  const method = testCase.method ?? "GET";
  const operationPath = testCase.operationPath ?? new URL(testCase.pageUrl).pathname;
  const expectedStatuses = testCase.expectedStatuses ?? [];
  const requestBody = testCase.requestBody;
  const headers =
    requestBody === undefined
      ? { accept: "application/json", ...(testCase.headers ?? {}) }
      : { accept: "application/json", "content-type": "application/json", ...(testCase.headers ?? {}) };
  lines.push("    const response = await request.fetch(");
  lines.push(`      apiUrl(${JSON.stringify(operationPath)}),`);
  lines.push("      {");
  lines.push(`        method: ${JSON.stringify(method)},`);
  lines.push(`        headers: ${JSON.stringify(headers)}${requestBody === undefined ? "" : ","}`);
  if (requestBody !== undefined) {
    lines.push(`        data: ${JSON.stringify(requestBody, null, 10).replace(/\n/g, "\n        ")}`);
  }
  lines.push("      }");
  lines.push("    );");
  lines.push("    const status = response.status();");
  if (expectedStatuses.length > 0) {
    lines.push(`    const expectedStatuses = ${JSON.stringify(expectedStatuses)};`);
    lines.push("    if (!expectedStatuses.includes(status)) {");
    lines.push("      throw new Error(`Expected documented status ${expectedStatuses.join(', ')} but got ${status}. Body: ${await responseSnippet(response)}`);");
    lines.push("    }");
  } else {
    lines.push("    if (status >= 500) {");
    lines.push("      throw new Error(`Expected a non-5xx API response but got ${status}. Body: ${await responseSnippet(response)}`);");
    lines.push("    }");
  }
}
