import type { CodeDecayReport } from "@submuxhq/codedecay-core";
import type { CheckConclusion, GitHubClient, GitHubComment } from "./types.js";

export const COMMENT_MARKER = "<!-- codedecay-github-app-report -->";
const CHECK_NAME = "CodeDecay";

export interface GitHubTarget {
  owner: string;
  repo: string;
  pullNumber: number;
  headSha: string;
}

export async function createAnalysisCheck(octokit: GitHubClient, target: GitHubTarget): Promise<number> {
  const response = await octokit.rest.checks.create({
    owner: target.owner,
    repo: target.repo,
    name: CHECK_NAME,
    head_sha: target.headSha,
    status: "in_progress",
    started_at: new Date().toISOString(),
    output: {
      title: "CodeDecay analysis started",
      summary: "CodeDecay is analyzing this pull request."
    }
  });

  return response.data.id;
}

export async function completeAnalysisCheck(options: {
  octokit: GitHubClient;
  target: GitHubTarget;
  checkRunId: number;
  conclusion: CheckConclusion;
  title: string;
  summary: string;
}): Promise<void> {
  await options.octokit.rest.checks.update({
    owner: options.target.owner,
    repo: options.target.repo,
    check_run_id: options.checkRunId,
    status: "completed",
    conclusion: options.conclusion,
    completed_at: new Date().toISOString(),
    output: {
      title: truncate(options.title, 255),
      summary: truncate(options.summary, 65_000)
    }
  });
}

export async function upsertPullRequestComment(options: {
  octokit: GitHubClient;
  target: GitHubTarget;
  markdown: string;
}): Promise<void> {
  const body = `${COMMENT_MARKER}\n${options.markdown.trim()}\n\n---\nGenerated by the CodeDecay GitHub App.`;
  const existing = await findExistingComment(options.octokit, options.target);

  if (existing) {
    await options.octokit.rest.issues.updateComment({
      owner: options.target.owner,
      repo: options.target.repo,
      comment_id: existing.id,
      body
    });
    return;
  }

  await options.octokit.rest.issues.createComment({
    owner: options.target.owner,
    repo: options.target.repo,
    issue_number: options.target.pullNumber,
    body
  });
}

export function checkSummaryForReport(report: CodeDecayReport): string {
  return [
    `Overall risk: ${report.summary.riskLevel}`,
    `Merge risk: ${report.summary.mergeRiskScore}/100`,
    `Decay risk: ${report.summary.decayScore}/100`,
    `Findings: ${report.summary.findingCounts.high} high, ${report.summary.findingCounts.medium} medium, ${report.summary.findingCounts.low} low`
  ].join("\n");
}

async function findExistingComment(
  octokit: GitHubClient,
  target: GitHubTarget
): Promise<GitHubComment | undefined> {
  const response = await octokit.rest.issues.listComments({
    owner: target.owner,
    repo: target.repo,
    issue_number: target.pullNumber,
    per_page: 100
  });

  return response.data.find((comment) => comment.body?.includes(COMMENT_MARKER));
}

function truncate(value: string, maxLength: number): string {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength - 3)}...`;
}
