import type { GitHubClient, GitHubComment } from "../types.js";
import type { GitHubTarget } from "./target.js";

export const COMMENT_MARKER = "<!-- codedecay-github-app-report -->";

export async function upsertPullRequestComment(options: {
  octokit: GitHubClient;
  target: GitHubTarget;
  markdown: string;
}): Promise<void> {
  const body = `${COMMENT_MARKER}\n${options.markdown.trim()}\n\n---\nGenerated by the CodeDecay GitHub App.`;
  const existing = await findExistingComment(options.octokit, options.target);

  if (existing) {
    await options.octokit.rest.issues.updateComment({
      owner: options.target.owner,
      repo: options.target.repo,
      comment_id: existing.id,
      body
    });
    return;
  }

  await options.octokit.rest.issues.createComment({
    owner: options.target.owner,
    repo: options.target.repo,
    issue_number: options.target.pullNumber,
    body
  });
}

async function findExistingComment(
  octokit: GitHubClient,
  target: GitHubTarget
): Promise<GitHubComment | undefined> {
  const response = await octokit.rest.issues.listComments({
    owner: target.owner,
    repo: target.repo,
    issue_number: target.pullNumber,
    per_page: 100
  });

  return response.data.find((comment) => comment.body?.includes(COMMENT_MARKER));
}
